[package]
name = "hamster_gfx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.22.0"
gl = "0.14.0"
glfw = "0.52.0"
image = "0.24.7"
cli-clipboard = "0.4.0"
glam = "0.24.2"
